### ISSUE TITLE
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3".

### ISSUE THREAD

**Issue by JayUnt** [danielstern/isomorphic-react#12]
I just pulled down the repo and ran `npm install && npm run postinstall`

When I run `npm run start-dev`, I get the following error:

C:\Projects\Playground\react\pluralsight\testing-react-applications-jest\isomorphic-react\node_modules\@babel\helper-plugin-utils\lib\index.js:72
  throw Object.assign(err, {
  ^

`Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry
that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.`

Any ideas?

**Comment by JayUnt** [comment]
It worked when i went back to babel 6.26, so i am doing that for now.

**Comment by ppywmjr** [comment]
It seems that the major version upgrade to babel v7 has a couple of things missing.
Firstly, the postinstall task still requests 6.26.3, I fixed this by changing that to latest v7, which is 
`babel-cli@7.0.0-beta.3`
that should fix your original error.
Secondly, babel v7 separates babel-node into a separate package, so in your dependencies you'll need to add that, eg: 
`"@babel/node": "^7.2.2"`
See the babel migration guide for details. https://babeljs.io/docs/en/v7-migration

**Comment by JayUnt** [comment]
those changes worked.  Thanks!

**Comment by awichmann-mintel** [comment]
I'm still getting this error. I have reverted back to commit f08c311 (`git reset --hard f08c311`), and this at least lets me run the jest.

**Comment by danielstern** [comment]
Looks like this is working for some users, not working for others. Will keep it at this commit for now.

**Comment by prashantnl** [comment]
Hi @danielstern @ppywmjr 
I am still facing this issue after copy-pasting package.json file.
I am doing a plural sight course and for initial server/index.js got this error.
`babel-node server/index.js`
I have the same .babelrc and package.json but still getting this issue. Any help.

**Comment by prashant753** [comment]
Hi @danielstern @ppywmjr 
I am still facing this issue after copy-pasting package.json file.
I am doing a plural sight course and for initial server/index.js got this error.
`babel-node server/index.js`
I have the same .babelrc and package.json but still getting this issue. Any help.

index.js file
```
import express from 'express';
import fs from 'fs-extra';

const port = process.env.PORT || 3000;
const app = express();
app.get(['/'], async (req, res) => {
    let index = await fs.readFile('./public/index.html', 'utf-8');
    res.send(index);
});

app.listen(port, '0.0.0.0', () => `App is listening on port ${port}`);
```
