### ISSUE TITLE
stateful component test failing

### ISSUE THREAD

**Issue by leongaban** [danielstern/isomorphic-react#20]
Demo clip on NotificationViewer: https://app.pluralsight.com/player?course=testing-react-applications-jest&author=daniel-stern&name=f31785ac-30f9-4d02-aab6-473c85ce6770&clip=8&mode=live

Stackoverflow question posted here: https://stackoverflow.com/questions/56637899/jest-stateful-component-with-async-function-failing-test

Pull-request with code here: https://github.com/danielstern/isomorphic-react/pull/19

I have the NotificationsViewer service mocked and am able to change count to `42` or `5`. However the test still fails and text is still `"Loading..."`

<img width="575" alt="Screen Shot 2019-06-18 at 11 36 59 AM" src="https://user-images.githubusercontent.com/191636/59702492-79cf8380-91bd-11e9-9976-12de274a1094.png">

It seems to me that the `await delay()` is not letting the life cycle methods run first before the `expect` block is tested. Because the results of `console.log('text is:', text);` are hit first, then the `componentDidMount` and `componentDidUpdate` logs are hit.

**Comment by leongaban** [comment]
This is now fixed! :D 

I needed to use Enzyme in my case in order to make sure that the `componentDidMount` was called.

https://stackoverflow.com/questions/56637899/jest-stateful-component-with-async-function-failing-test/56655333#56655333

**Comment by danielstern** [comment]
Merged thanks a lot for this quick fix!
