### ISSUE TITLE
First clone of master doesn't match beginning of pluralsight class

### ISSUE THREAD

**Issue by diberry** [danielstern/isomorphic-react#25]
This isn't a big deal for experienced devs but for beginners it may be a problem.

I cloned the repo then followed the instructions in the pluralsight course on testing react. Jest isn't supposed to be installed and there aren't supposed to be any tests.

I get the following output from running master that isn't in the video

Ran all test suites.
  console.warn src/services/__mocks__/NotificationsService.js:8
    GOOD JOB! USING MOCK SERVICE

  console.warn src/services/__mocks__/NotificationsService.js:8
    GOOD JOB! USING MOCK SERVICE

  console.warn src/services/__mocks__/NotificationsService.js:8
    GOOD JOB! USING MOCK SERVICE

  console.log src/components/NotificationsViewer.jsx:15
    componentDidMount count: 42

  console.log src/components/NotificationsViewer.jsx:23
    componentDidUpdate count: 42

  console.log src/components/NotificationsViewer.jsx:15
    componentDidMount count: 42

  console.log src/components/NotificationsViewer.jsx:23
    componentDidUpdate count: 42

  console.log src/components/NotificationsViewer.jsx:15
    componentDidMount count: 42

  console.log src/components/NotificationsViewer.jsx:23
    componentDidUpdate count: 42

  console.log src/components/NotificationsViewer.spec.js:39
    text is: 42 Notifications Awaiting

**Comment by danielstern** [comment]
Thank you, Will look into this but in the mean time please feel free to submit a PR.

**Comment by pav-w** [comment]
still the same for me

**Comment by danielstern** [comment]
This is probably the result of another well-intentioned but incorrect PR. I'm looking into it but if anyone has already worked around this, a PR would be great!
