### ISSUE TITLE
Having issue with start ? 

### ISSUE THREAD

**Issue by bavilari93** [danielstern/isomorphic-react#26]
made a few modifications on the webpack config 
`const path = require('path');
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');
const webpack = require('webpack');

/**
 * Production Webpack Config bundles JS, then uglifies it and exports it to the "dist" directory
 * See Development webpack config for detailed comments
 */
module.exports = {
    mode: 'development',
    entry: [
        'babel-regenerator-runtime',
        path.resolve(__dirname, 'src')
    ],
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'bundle.js',
        publicPath: '/'
    },
    optimization: {
        minimizer: [
            // we specify a custom UglifyJsPlugin here to get source maps in production
            new UglifyJsPlugin({
              cache: true,
              parallel: true,
              uglifyOptions: {
                compress: false,
                ecma: 6,
                mangle: true
              },
              sourceMap: true
            })
          ]
      },
    plugins: [
        new webpack.DefinePlugin({
            'process.env': {
                NODE_ENV: JSON.stringify('production'),
                WEBPACK: true
            }
        }),
        /**
         * Uglifies JS which improves performance
         * React will throw console warnings if this is not implemented
         */
       
    ],
    resolve: {
        extensions: ['.js', '.json', '.jsx'],
    },
    module: {
        rules: [
            {
                test: /\.jsx?$/,
                use: {
                    loader: 'babel-loader'
                },
                include: path.resolve(__dirname, 'src')
            }
        ]
    }
};`

in case you are having error none related to this : 
I also tried rm -rf node_modules && npm cache clean --force && npm install

**Comment by danielstern** [comment]
Good work! Happy to look at a pull request that integrates this.

**Comment by GaddMaster** [comment]
Please use the code icon when writing code, reading your code above is not possible, worse nightmare stuff
Example
```
module.exports = {
mode: 'development',
entry: [
'babel-regenerator-runtime',
path.resolve(__dirname, 'src')
],
output: {
path: path.resolve(__dirname, 'dist'),
filename: 'bundle.js',
publicPath: '/'
},
optimization: {
minimizer: [
// we specify a custom UglifyJsPlugin here to get source maps in production
new UglifyJsPlugin({
cache: true,
parallel: true,
uglifyOptions: {
compress: false,
ecma: 6,
mangle: true
},
sourceMap: true
})
]
},
plugins: [
new webpack.DefinePlugin({
'process.env': {
NODE_ENV: JSON.stringify('production'),
WEBPACK: true
}
}),
/*
* Uglifies JS which improves performance
* React will throw console warnings if this is not implemented
*/

],
resolve: {
extensions: ['.js', '.json', '.jsx'],
},
module: {
rules: [
{
test: /.jsx?$/,
use: {
loader: 'babel-loader'
},
include: path.resolve(__dirname, 'src')
}
]
}
};
```

**Comment by jvcjunior** [comment]
I'm still having issue to start. Any news on this one?
