### ISSUE TITLE
require("history").createMemoryHistory issue 

### ISSUE THREAD

**Issue by moesi88** [danielstern/isomorphic-react#28]
` Please use `require("history").createMemoryHistory` instead of `require("history/createMemoryHistory")`. Support for the latter will be removed in the next major release`

i got this error tried to work around it but still cant be resolved

**Comment by danielstern** [comment]
Excellent.

Looks terrific.

Would you be able to put together a PR?

DS
________________________________

**Comment by GaddMaster** [comment]
Let me know. If not Id is happy to make that pr, only small changes !

**Comment by jvcjunior** [comment]
any news on this one?

**Comment by svendster** [comment]
I was getting this error, too, but the following steps resolved it for me:

- git clone https://github.com/danielstern/isomorphic-react.git
- cd isomorphic-react
- npm update
- npm audit fix
- npm run-script build
- npm start
