### ISSUE TITLE
Isomorphic-react not running in 2020.

### ISSUE THREAD

**Issue by raydot** [danielstern/isomorphic-react#29]
I can't get the course files to run.  I get a lot of errors mostly related to the fact that Babel no longer supports es2015.

First error is a problem with Uglify:
```
ERROR in bundle.js from UglifyJs
Unexpected token: punc (}) [bundle.js:5644,0]
```

Then a MODULE_NOT_FOUND error from cross-env
```
{
  code: 'MODULE_NOT_FOUND'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! isomorphic-react@1.0.0 build: `cross-env webpack --config ./webpack.config.prod.babel.js`

```

It doesn't get much better from there.  Any chance you're feeling like updating this course for 2020?

**Comment by danielstern** [comment]
Hello.

Try cloning the main repository with completed application (updated for Babel) and taking it from there.
________________________________

**Comment by swapnilvjoshi** [comment]
I was facing the same issue However I have disabled the uglify and the project works now.

![image](https://user-images.githubusercontent.com/47324373/73735674-f0ff5b00-473f-11ea-86e3-c6f01293b749.png)

**Comment by GaddMaster** [comment]
I had same issue. It was a line of code in the webpack file that minimizes the js. Needs be removed for and updated choice.

Dan

**Comment by GaddMaster** [comment]
Issue #17 shows solutions, exactly what I did!

**Comment by raydot** [comment]
I cloned the full version and took it from there as suggested above.  Wasn't as exciting but...

I'm gonna close this although anyone who comes along later with questions please feel free to ask!
