### ISSUE TITLE
Stop the app to make ajax call for home page

### ISSUE THREAD

**Issue by elhampour** [danielstern/isomorphic-react#3]
when we make a get request to home page of the app, for example through the browser, the ajax call to get the list of all questions is redundant, because of server side rendering, we have populate the list of question from server, 

so how can stop the app to make ajax request when the html is rendered from server ?

**Comment by elhampour** [comment]
I found the solution . its because of the store.
we should send the store from server to client. 
you can do it in a lot of ways. but i think the straight forward way to do it is to pass store through the html.

**Comment by GaddMaster** [comment]
This other project which has a different approach to server-side rendering does exactly this !!!!

https://github.com/StephenGrider/ReactSSRCasts
