### ISSUE TITLE
Bundle Size Warning !

### ISSUE THREAD

**Issue by GaddMaster** [danielstern/isomorphic-react#30]
Hi Daniel

Curious question @danielstern 

Your completely basic program gets warnings for bundle size as is (Production Build, Untouched), which is concerning?

I'm thinking this app is super small, but still hits them limits already.

What kinda bundle sizes are you getting with this basic app?

Is all the server stuff bundled in for the client in this app?

Suppose I am assuming I can reduce prod size to the very low right using your structure?

Thoughts?

Daniel Gadd

**Comment by GaddMaster** [comment]
@danielstern bump :(

**Comment by danielstern** [comment]
Hey Daniel.

This is probably because React is being bundled along with.

This is convenient, but you can achieve faster performance by making it an external and using a CDN.

Hope that helps!

DS
________________________________

**Comment by GaddMaster** [comment]
WOW ! That was not the main reason but this just took off a huge chunk. I add a script tag src. Only when that arrives, it bootstraps and takes over utilizing my bundle?
