### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by oluwadareseyi** [danielstern/isomorphic-react#35]
I keep getting this error whenever I run the project:

```WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.```

**Comment by danielstern** [comment]
Sounds like you may be using a different version of Webpack than the one in the example.

Try installing the same version (via package.json)
________________________________

**Comment by shootermv** [comment]
I have similar error. (im running winodws10 , node 10.19.0)
Managed to run the project using: ```npx babel-node server```

**Comment by kicsigabszi** [comment]
Same here

**Comment by oluwadareseyi** [comment]
I'll try it out, thanks.

**Comment by Stu1986c** [comment]
Having the same problem here. Cloned the repo afresh, run the commands as per the Getting Started instructions and getting the above error

**Comment by Naveen-Gupta** [comment]
Same here

**Comment by annie-elequin** [comment]
I ran `npm i -g webpack webpack-cli` - it did update them to the latest version (4.42.1 at time of writing) and this matches what's in the package.json, but I'm still getting the error 😔

**Comment by danielstern** [comment]
I see, looks like possibly the version of a different tools has fallen out of sync. Try cloning the entire repository and working backwards from there.
________________________________
