### ISSUE TITLE
Resolve Alias Support Additions

### ISSUE THREAD

**Issue by fantypants** [danielstern/isomorphic-react#44]
****[Found the solution -- At end]****
* I've left the question here in case any one else comes across this issue *
*****************************************

Hello,
I've been adapting a current project to a isomorphic app (from CRA + Prerender).

I've heavily used aliases within the code base, I've been trying to get them to work with your setup, however it can never find the module:

`import TagsList from 'components/TagsList'` (not working) instead of `import TagsList from './TagsList'` (working)

Usually the resolves have been working fine with a webpack config such as the below:

`resolve: {
    extensions: ['*', '.js', '.jsx'],
		alias: {
      components: path.resolve(__dirname, 'src/components')
}`

However, within the scope of express, babel-node & webpack:
`webpack --mode production` correctly builds the project
`cross-env NODE_ENV=development babel-node server --useServerRender=true --useLiveData=false` results in the aliased modules not found.

Could this be a bundle issue from webpack? --Babel needs the alias
I believe I've missed something, or Am I doing the resolves wrong with babel? Babel needed the alias, hence why it worked with production.
Is there any specific way to use resolves so aliasing works? -- Module Resolver

SOLUTION:

Use: https://www.npmjs.com/package/babel-plugin-module-resolver
`["module-resolver", { "root": ["./src"],"alias": {"components": "./src/components"}}]`

**Comment by danielstern** [comment]
Happy to see a PR for this

**Comment by fantypants** [comment]
Apologies for the delay Daniel; I'll have a look into the configuration again to see for the PR, our App is well and truly beyond this context now, however, when I get a quiet moment I'll check & implement a correct PR for it.

**Comment by danielstern** [comment]
Hey Matthew! No problem. As always our professional commitments must be judiciously balanced with our open source interests!
________________________________
