### ISSUE TITLE
Incorrect configuration in package json for dependency

### ISSUE THREAD

**Issue by gahlotbaba** [danielstern/isomorphic-react#49]
All the packages are showing under dependency. Can you please confirm if this is the right way? Is there no major difference between dependency and devDependency?  Will all web-pack and other local/dev related package will not be part of production build?

**Comment by danielstern** [comment]
Hey Mohit.

Certain packages that would be dev-dependencies are dependencies to make it simpler to deploy, These could definitely be moved to dev dependencies for projects which grow to that size.
