### ISSUE TITLE
Not changed styles by HMR after route change

### ISSUE THREAD

**Issue by ShiiRochi** [danielstern/isomorphic-react#5]
I added the following button to the detailed view of record, lets call it **RootButton**, and met some kind of a bug.
The following code it related to the button:
`<Link to={'/'}><Button block={true} color="warning" size="small">Back</Button></Link>`
The problem is, that everytime when I change button's color property, HMR seems to work properly and it is visible that, for example, **warning** has changed to **primary** and button changed its representation, however if I will go to the root page and then click on another "More info" button, then this LinkButton of that record page will look oldstyled, i.e. with **warning** style.

**Comment by GaddMaster** [comment]
I have a similar issue where I changed CSS and nothing happens. 
Are you sure you javascript is on because it needs to be on for the HMR to take effect I do believe 
Dan
