### ISSUE TITLE
request: solutions to challenges

### ISSUE THREAD

**Issue by lisaross** [danielstern/isomorphic-react#6]
I know it makes it less of a challenge, in a way, but it would be awesome if there was a repo or branch that I could look at while I'm working out the challenges. Sometimes it's a wee syntax error (or a much broader understanding issue) that seeing the correct result would help me understand. I get it if you don't want to put that work in, but I had to ask 😄 

PS. AWESOME course, and I'm excited to see other Ontarians doing the good work!

**Comment by danielstern** [comment]
Hey Lisa!

Thank you for the excellent suggestion. I considered doing this, but I decided that there are multiple correct ways to solve the challenges, and so did not want to interpose a solution myself.

Good luck, and I'm sure you will have the challenges solved soon!

DS


________________________________
Daniel Stern | CEO
Ishimura Capital Partners
________________________________
